In [16]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv( '/Users/antique/Desktop/lr-data 2.csv', names=['x1','x2','y']) 
#df.head()
X = df.iloc[:, 0:2].values
y = df.iloc[:, 2].to_frame().values
m = len(X)
ones = np.ones((m,1))

X = np.hstack((ones, X))
alpha = 0.01
num_iters = 400
theta = np.zeros((X.shape[1],1))


print(X.shape, y.shape, theta.shape,)

def sigmoid(z):
    return 1/(1+np.exp(-z))

def cost_function(X, y, theta): #cost J
    m = y.size
    h = sigmoid(X.dot(theta))

    J =(-1/m) * ( np.dot( np.log(h).T , y) + np.dot( np.log(1-h).T, (1-y)) )

    return np.inf if np.isnan(J[0]) else J[0]

def predict(x, theta):
    return sigmoid(x.dot(theta))

'''def gradientDescent(x, y, theta, alpha, m, numIterations):
    J_history = np.zeros(shape=(numIterations, 1))
    xTrans = x.transpose()
    for i in range(0, numIterations):
        hypothesis = 1.0 / (1.0 + np.exp((-1) *np.dot(x, theta)))
        #calculates the hypothesis by multiplying the parameter theta with input and the value is subjected to the sigmoid function
        loss = hypothesis - y 
        #calculats the difference between the hypothesis and the actual value
        cost = (-1)*np.sum((y*np.log(hypothesis)) + ((1-y)*np.log(1-hypothesis))) / (m)
        #calculates the cost function for logistic regression
        gradient = np.dot(xTrans, loss) / m
        # update
        theta = theta - alpha * gradient
        J_history[i][0] = cost
    return theta, J_history
'''
def gradientDescent(X, y, theta, alpha, m = len(y), num_iters = 4000):
    m = len(y) # number of training examples
    J_history = np.zeros((num_iters, 1))
    
    for iter in range(num_iters):
        h = sigmoid(X.dot(theta))
        theta = theta - alpha*(1/m)*(X.T.dot(h-y))
        
        J_history[iter] = cost_function(X, y, theta)
        
    return(theta, J_history)


(47, 3) (47, 1) (3, 1)


In [17]:
cost_function( X, y, theta)

array([0.69314718])

In [18]:
theta, jh = gradientDescent(X, y, theta, alpha, len(y), 400)
theta

/Users/antique/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:26: RuntimeWarning: divide by zero encountered in log


array([[-0.26379376],
       [ 0.29919751],
       [ 0.18741676]])

In [19]:
sigmoid(np.array([1,45,85]).dot(theta))

array([1.])