In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [2]:
rawData = np.loadtxt('/Users/antique/Desktop/ml/ex1data2.txt', delimiter=',')

In [3]:
"""
2104,3,399900
1600,3,329900
2400,3,369000
1416,2,232000
3000,4,539900
"""
def printHead(data):
    print(data[1:6,:])
    return

In [4]:
#dataX is raw matrix without all the 1s at first column
dataX=rawData[:,0:2]
mu=np.array([np.mean(dataX[:,0]),np.mean(dataX[:,1])])
sigma=np.array([np.std(dataX[:,0]),np.std(dataX[:,1])])

In [5]:
#np.mean(dataX[:,0])

In [6]:
sigma


array([7.86202619e+02, 7.52842809e-01])

In [7]:
mu

array([2000.68085106,    3.17021277])

In [8]:
printHead(dataX)

[[1.600e+03 3.000e+00]
 [2.400e+03 3.000e+00]
 [1.416e+03 2.000e+00]
 [3.000e+03 4.000e+00]
 [1.985e+03 4.000e+00]]


In [21]:
sum(a[:,:])

array([-4.44089210e-16,  1.14075416e-14])

In [18]:
np.sum(a[:,0])

4.440892098500626e-16

In [17]:
np.sum(a[:,1])

1.2739809207573671e-14