In [1]:
import numpy as np

In [2]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)

In [3]:
c.shape

(12288, 45)

In [6]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

In [12]:
a

array([[ 0.79261999,  0.2033704 , -0.20771169],
       [ 1.66672769,  0.32189327, -0.89079315],
       [-0.21373132,  0.3994311 ,  0.61724439]])

In [13]:
b

array([[-1.15900471],
       [-0.16641734],
       [ 0.36975698]])

In [14]:
c

array([[-0.9186503 , -0.23570725,  0.24073882],
       [-0.27737239, -0.05356862,  0.14824343],
       [-0.07902865,  0.14769244,  0.22823042]])

In [16]:
a[0,0]*b[0,0]

-0.9186503003703531